# Generated by Django 2.1.5 on 2019-02-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20190225_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='goods',
            new_name='name',
        ),
    ]
