# Generated by Django 2.1.5 on 2019-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20190226_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_cart',
            name='ljgm',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='立即购买'),
        ),
    ]
