# Generated by Django 2.1.5 on 2019-02-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_shop_cart_ljgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='itmes',
            field=models.CharField(max_length=50, null=True, verbose_name='订单号'),
        ),
    ]
