# Generated by Django 2.1.5 on 2019-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20190226_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_goods',
            name='goods',
            field=models.IntegerField(null=True, verbose_name='hehe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
