# Generated by Django 2.1.5 on 2019-02-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20190228_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_goods',
            name='itme_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Order', verbose_name='订单编号'),
        ),
    ]
